version: "3"

services:
    
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    links:
      - ckan-web
    ports:
      - "8081:80"
    labels:
      # Lagoon Labels
      lagoon.type: nginx

  ckan-worker:
    container_name: ckan-worker
    build:
      context: .
      dockerfile: ckan-worker/Dockerfile
      args:
        - TZ=${TZ}
    env_file:
      - .env
    links:
      - db
      - solr
      - redis
    ports:
      - "8800:8800"
    labels:
      # Lagoon Labels
      lagoon.type: cli
    environment:
      # Defaults work with linked containers, change to use own Postgres, SolR, Redis or Datapusher
      - CKAN_SQLALCHEMY_URL=${CKAN_SQLALCHEMY_URL}
      - CKAN_DATASTORE_WRITE_URL=${CKAN_DATASTORE_WRITE_URL}
      - CKAN_DATASTORE_READ_URL=${CKAN_DATASTORE_READ_URL}
      - CKAN_SOLR_URL=${CKAN_SOLR_URL}
      - CKAN_REDIS_URL=${CKAN_REDIS_URL}
      - CKAN_SITE_URL=${CKAN_SITE_URL}
      - CKAN_SITE_TITLE=${CKAN_SITE_TITLE}
      - CKAN_MAX_UPLOAD_SIZE_MB=${CKAN_MAX_UPLOAD_SIZE_MB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
      - CKAN_PORT=${CKAN_PORT}
  
  ckan-web:
    container_name: ckan-web
    build:
      context: .
      dockerfile: ckan-web/Dockerfile
      args:
        - TZ=${TZ}
    env_file:
      - .env
    links:
      - ckan-worker    
      - db
      - solr
      - redis
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    labels:
      # Lagoon Labels
      lagoon.type: python
    environment:
      # Defaults work with linked containers, change to use own Postgres, SolR, Redis or Datapusher
      - CKAN_SQLALCHEMY_URL=${CKAN_SQLALCHEMY_URL}
      - CKAN_DATASTORE_WRITE_URL=${CKAN_DATASTORE_WRITE_URL}
      - CKAN_DATASTORE_READ_URL=${CKAN_DATASTORE_READ_URL}
      - CKAN_SOLR_URL=${CKAN_SOLR_URL}
      - CKAN_REDIS_URL=${CKAN_REDIS_URL}
      - CKAN_SITE_URL=${CKAN_SITE_URL}
      - CKAN_SITE_TITLE=${CKAN_SITE_TITLE}
      - CKAN_MAX_UPLOAD_SIZE_MB=${CKAN_MAX_UPLOAD_SIZE_MB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
      - CKAN_PORT=${CKAN_PORT}
    volumes:
      - ckan_storage:/var/lib/ckan

  db:
    container_name: db
    image: uselagoon/postgres-11
    volumes:
      - db_data:/var/lib/postgresql/data
    labels:
      # Lagoon Labels
      lagoon.type: postgres-single

  datastore:
    container_name: datastore
    image: uselagoon/postgres-11
    volumes:
      - datastore_data:/var/lib/postgresql/data
    labels:
      # Lagoon Labels
      lagoon.type: postgres-single

  solr:
    container_name: solr
    build:
      context: solr/
      dockerfile: Dockerfile
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index
    labels:
      # Lagoon Labels
      lagoon.type: solr

  redis:
    container_name: redis
    image: amazeeio/redis:6-latest
    labels:
      # Lagoon Labels
      lagoon.type: redis

volumes:
  ckan_storage:
  db_data:
  datastore_data:
  solr_data: